version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.15.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo dpkg --add-architecture i386
      - run: sudo apt update
      - run: sudo apt install -y wine32 wine64 wine
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}        
      - run: yarn test
      - run: yarn package
      - run: node script/release.js